#!/bin/sh

# List of supported file extensions
SUPPORTED_FORMATS=(.mp4 .mkv .mov .avi .mpg .mpeg .m4v .wmv .flv .webm .mp3 .wav .ogg .flac .aac .m4a .ac3 .dts)

# Check if input file is provided
if [ $# -eq 0 ]; then
  echo "Error: Input file is required."
  exit 1
fi

# Get the input file
INPUT_FILE=$1

# Check if the input file has a supported extension
echo "Checking file extension..."
FILE_EXTENSION=${INPUT_FILE##*.}
echo -e "File extension found: $FILE_EXTENSION\n\n"
if [[ ! " ${SUPPORTED_FORMATS[@]} " =~ " .${FILE_EXTENSION} " ]]; then
  echo -e "Error extracting cover art:\nUnsupported file format. Supported formats are: ${SUPPORTED_FORMATS[@]}"
  exit 1
fi

# Get the output file name
OUTPUT_FILE=cover.jpg

# Try to extract the cover art using ffmpeg
ffmpeg -i "$INPUT_FILE" -vcodec copy -an -sn -map_metadata 0 -f mjpeg -y "$OUTPUT_FILE"
ret=$?
if [ $ret -eq 0 ]; then
  echo -e "\n\n\n\n\nCover art successfully extracted to $OUTPUT_FILE"
else
  echo -e "\n\n\n\n\nError extracting cover art:\n$ret"
fi
